### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/hardware/biometrics/BiometricPrompt$Builder;

### ISSUE THREAD

**Issue by vym4** [Kieun/android-biometricprompt#4]
I  have following dependencies: 

    implementation 'androidx.appcompat:appcompat:1.0.0-alpha1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0-alpha1'
    implementation 'com.google.android.material:material:1.0.0-alpha1'

I am getting above runtime error for line: 

   // Create biometricPrompt
                mBiometricPrompt = new BiometricPrompt.Builder(this)
                        .setDescription("Description")
                        .setTitle("Title")
                        .setSubtitle("Subtitle")
                        .setNegativeButton("Cancel", getMainExecutor(), new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialogInterface, int i) {
                                Log.i(TAG, "Cancel button clicked");
                            }
                        })
                        .build();

Tried changing dependencies and all but nothing helps.

 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/hardware/biometrics/BiometricPrompt$Builder;
        at com.prsnls.view.ui.LoginFragment.displayBiometricPrompt(LoginFragment.java:128)
        at com.prsnls.view.ui.LoginFragment.access$000(LoginFragment.java:38)
        at com.prsnls.view.ui.LoginFragment$1.onClick(LoginFragment.java:58)
        at android.view.View.performClick(View.java:6896)
        at android.widget.TextView.performClick(TextView.java:12689)
        at android.view.View$PerformClick.run(View.java:26088)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.hardware.biometrics.BiometricPrompt$Builder" on path: DexPathList[[zip file "/data/app/com.vog.prsnls-NnHPBLCkb3x5XwI9U8GNlA==/base.apk"],nativeLibraryDirectories=[/data/app/com.vog.prsnls-NnHPBLCkb3x5XwI9U8GNlA==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.prsnls.view.ui.LoginFragment.displayBiometricPrompt(LoginFragment.java:128) 
        at com.prsnls.view.ui.LoginFragment.access$000(LoginFragment.java:38) 
        at com.prsnls.view.ui.LoginFragment$1.onClick(LoginFragment.java:58) 
        at android.view.View.performClick(View.java:6896) 
        at android.widget.TextView.performClick(TextView.java:12689) 
        at android.view.View$PerformClick.run(View.java:26088) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6940) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by Kieun** [comment]
https://developer.android.com/reference/androidx/biometrics/BiometricPrompt
How about referring above url? It seems that Google provides BiometricPrompt.PromptInfo instead of BiometricPrompt build. I think they should fix it.

**Comment by ronakmob** [comment]
I am facing same issue for Samsung device running 7.0 , However this code works fine for the Android 9.0 Pixel 2 device.

@Kieun  I see `BiometricPrompt.PromptInfo ` is not available for the current compile version code (28), I have checked Android code. However I am able to find rest of 3 nested classes.

**Comment by ronakmob** [comment]
@Kieun  I made some research and come to know that `BiometricPrompt` BometricPrompt can be used only on Android P and above only.

Reference: https://medium.com/appnroll-publication/what-is-new-in-android-p-biometricprompt-d4fc85e55608

**Comment by victorlapin** [comment]
Use
implementation "androidx.biometric:biometric:1.0.0-alpha02"

**Comment by sairajkishore** [comment]
> Use
> implementation "androidx.biometric:biometric:1.0.0-alpha02"
still shows the same issue, is there any work around for this??

**Comment by victorlapin** [comment]
If you really are using androidx dependency, you shouldn't see android.hardware references in your code.

**Comment by sairajkishore** [comment]
> If you really are using androidx dependency, you shouldn't see android.hardware references in your code.
Thanks for the suggestion.
Yes the issue is resolved when using androidx imports, but still in O and older versions the finger print images are not displaying.

**Comment by Kieun** [comment]
Check latest codes
